// LIB — Book cover images from David Keener's library.


// Book Covers (150 x 250).
var pub_lib = [
["https://www.amazon.com/dp/B00AP8YZI0/?tag=keenertech-20",
    "https://gallery.davidkeener.org/lib/1633.jpg",
    "1633"],
["https://www.amazon.com/dp/B08MLNK1NK/?tag=keenertech-20",
    "https://gallery.davidkeener.org/lib/agent_of_the_imperium.jpg",
    "Agent of the Imperium"],
["https://www.amazon.com/dp/0671577794/?tag=keenertech-20",
    "https://gallery.davidkeener.org/lib/bolo_rising.png",
    "Bolo Rising"],
["https://www.amazon.com/dp/B003L1ZZFK/?tag=keenertech-20",
    "https://gallery.davidkeener.org/lib/cowboy_fengs.png",
    "Cowboy Feng's Space Bar and Grille"],
["https://www.amazon.com/dp/B002H8OS06/?tag=keenertech-20",
    "https://gallery.davidkeener.org/lib/draco_tavern.png",
    "The Draco Tavern"],
["https://www.amazon.com/dp/B013BEE32M/?tag=keenertech-20",
    "https://gallery.davidkeener.org/lib/forlorn_hope.png",
    "The Forlorn Hope"],
["https://www.amazon.com/dp/B0997VH2VP/?tag=keenertech-20",
    "https://gallery.davidkeener.org/lib/investigator.jpg",
    "The Investigator"],
["https://www.amazon.com/dp/B00H6SOV1S/?tag=keenertech-20",
    "https://gallery.davidkeener.org/lib/kalin.png",
    "Kalin (Dumarest #4)"],
["https://www.amazon.com/dp/B00PI181I4/?tag=keenertech-20",
    "https://gallery.davidkeener.org/lib/midsummer_tempest.png",
    "A Midsummer Tempest"],
["https://www.amazon.com/dp/B086T5Y5FP/?tag=keenertech-20",
    "https://gallery.davidkeener.org/lib/mamelukes.jpg",
    "Mamelukes"],
["https://www.amazon.com/dp/B0CS2J126H/?tag=keenertech-20",
    "https://gallery.davidkeener.org/lib/lonesome_october.jpg",
    "A Night in the Lonesome October"],
["https://www.amazon.com/dp/B00H6SOTL0/?tag=keenertech-20",
    "https://gallery.davidkeener.org/lib/polymath.jpg",
    "Polymath"],
["https://www.amazon.com/dp/B00F3KXN1U/?tag=keenertech-20",
    "https://gallery.davidkeener.org/lib/pride_of_chanur.png",
    "The Pride of Chanur"],
["https://www.amazon.com/dp/B0G2TVPJFH/?tag=keenertech-20",
    "https://gallery.davidkeener.org/lib/skull_x_bones.png",
    "Skull X Bones"],
["https://www.amazon.com/dp/B071KDK824/?tag=keenertech-20",
    "https://gallery.davidkeener.org/lib/starborn.png",
    "Starborn"],
["https://www.amazon.com/dp/B016CQUL3G/?tag=keenertech-20",
    "https://gallery.davidkeener.org/lib/star_fox.png",
    "The Star Fox"],
["https://www.amazon.com/dp/B005H0SY56/?tag=keenertech-20",
    "https://gallery.davidkeener.org/lib/ventus.png",
    "Ventus"],
["https://www.amazon.com/dp/B08XYRSMRL/?tag=keenertech-20",
    "https://gallery.davidkeener.org/lib/white_wing.png",
    "White Wing"]
];
